// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADi4O1kJyMn0_CKWCjLy_0wimk9MR9CfM',
    appId: '1:227220918976:web:1d5c615dc0960690449325',
    messagingSenderId: '227220918976',
    projectId: 'my-conquer-p',
    authDomain: 'my-conquer-p.firebaseapp.com',
    storageBucket: 'my-conquer-p.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyJNmBnaChZnaPmjsc5kSazPTrX_C_ZA4',
    appId: '1:227220918976:android:17643d6abbea8150449325',
    messagingSenderId: '227220918976',
    projectId: 'my-conquer-p',
    storageBucket: 'my-conquer-p.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBtmlxNyad64Bw6-GNirsVCEI959EeQt4',
    appId: '1:227220918976:ios:b9505e398a6af899449325',
    messagingSenderId: '227220918976',
    projectId: 'my-conquer-p',
    storageBucket: 'my-conquer-p.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBtmlxNyad64Bw6-GNirsVCEI959EeQt4',
    appId: '1:227220918976:ios:5d0eb43417e5c02e449325',
    messagingSenderId: '227220918976',
    projectId: 'my-conquer-p',
    storageBucket: 'my-conquer-p.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
